name: Test

on:
  workflow_dispatch:  # Manual execution only - you control when tests run

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.13.7"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r custom_components/netro_watering/requirements.test.txt
    
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: |
        python -m pytest tests/components/netro_watering/ -v