name: CI

on:
  push:
    branches: [ main ]  # Run tests on pushes to main and develop branches
  pull_request:
    branches: [ main ]           # Run tests on PRs targeting main branch
  workflow_dispatch:  # Manual execution only - you control when tests run

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.13.7"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r custom_components/netro_watering/requirements.test.txt
    
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run tests with coverage
      run: |
        python -m pytest tests/ -v --cov=custom_components.netro_watering --cov-report=xml
        echo "=== Coverage Summary ==="
        python -m coverage report --show-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false